### PR TITLE
Enable July code freeze

### PR DESCRIPTION
**Pull request by smlambert**
Temporarily freeze some repos for July release

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
I suppose a mechanism for a branch specific code freeze is not in place yet?

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by gdams — APPROVED** [review]

**Comment by smlambert** [comment]
> I suppose a mechanism for a branch specific code freeze is not in place yet?

Believe https://github.com/adoptium/.github/issues/121 put it in place

**Comment by jerboaa** [comment]
> > I suppose a mechanism for a branch specific code freeze is not in place yet?
> 
> Believe #121 put it in place

Got it, thanks!

**Pull request merged**
